config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  root to: 'recipes#index'

  resources :recipes, only: %i[index new create edit update show] do
    post 'add_list', on: :member
    post 'published', on: :member
    post 'reviewed', on: :member
  end
  resources :recipe_lists, only: %i[new create show]
  resources :recipe_types, only: %i[new create]

  get 'my_recipes', to: 'recipes#my_recipes'
  get 'my_list', to: 'recipe_lists#my_list'
  get 'search', to: 'recipes#search'
  get 'list_pending', to: 'recipes#list_pending'

  namespace :api do
    namespace :v1 do
      resources :recipes, only: %i[show create destroy]
      resources :recipe_types, only: %i[show create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, :recipe_type, :cuisine, :difficulty, :cook_time,
            :ingredients, :cook_method, presence: true

  belongs_to :recipe_type
  belongs_to :user
  belongs_to :cuisine

  has_many :recipe_list_item
  has_many :recipe_list, through: :recipe_list_item

  enum status: { pending: 0, published: 10, reviewed: 20 }

  def cook_time_min
    "#{cook_time} minutos"
  end
end

app/models/recipe_list.rb
class RecipeList < ApplicationRecord
  belongs_to :user

  has_many :recipe_list_item
  has_many :recipes, through: :recipe_list_item

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/recipe_list_item.rb
class RecipeListItem < ApplicationRecord
  belongs_to :recipe
  belongs_to :recipe_list

  # validates :recipe, uniqueness: { message: 'Receita já adicionada!' }
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes

  validates :name, presence: true
  validates :name, uniqueness: { message: 'Tipo de receita já cadastrado' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes

  has_many :recipe_lists
  has_many :recipe_list_item, through: :recipe_lists
  has_many :recipes_on_list, through: :recipe_list_item, source: :recipe

  def is_owner?(recipe)
    true if recipe.user == self
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API

end

app/controllers/api/v1/recipe_types_controller.rb
# frozen_string_literal: true

class Api::V1::RecipeTypesController < Api::V1::ApiController
  # before_action :set_params_id, only: %i[show]

  def show
    recipe_type = RecipeType.find(params[:id])
    render json: recipe_type.recipes, status: :ok
  rescue ActiveRecord::RecordNotFound
    render json: { msg: 'Tipo de receita não cadastrada' }, status: 404
  end

  def create
    recipe_type = RecipeType.new(set_params)

    if recipe_type.save
      render json: recipe_type, status: 201
    else
      render json: { errors: recipe_type.errors.full_messages }, status: 412
    end
  end

  private

  def set_params_id
    recipe_type = RecipeType.find(params[:id])
  end

  def set_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::ApiController
  # before_action :set_params_id, only: %i[show]

  def show
    recipe = Recipe.find(params[:id])
    render json: recipe, status: 200
  end

  def create
    recipe = Recipe.new(set_params)

    if recipe.save
      render json: recipe, status: 201
    else
      render json: { errors: recipe.errors.full_messages }, status: 412
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    render json: {}, status: 202

  rescue ActiveRecord::RecordNotFound
    render json: { msg: 'Receita deletada com sucesso' }, status: 404
  end

  private

  def set_params_id
    @recipe = Recipe.find(params[:id])
  end

  def set_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id, :difficulty,
                                    :cook_time, :ingredients, :cook_method, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipe_lists_controller.rb
class RecipeListsController < ApplicationController
  def new
    @recipe_list = RecipeList.new
  end

  def create
    @recipe_list = RecipeList.new(params.require(:recipe_list).permit(:name))
    @recipe_list.user = current_user
    if @recipe_list.save
      flash[:alert] = 'Lista criada com sucesso'
      redirect_to @recipe_list
    else
      flash.now[:alert] = 'Já possui uma lista com este nome'
      render :new
    end
  end

  def show
    @recipe_list = RecipeList.find(params[:id])
  end

  def my_list
    @recipe_lists = current_user.recipe_lists
    @recipe_list_items = current_user.recipe_list_item
  end

end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))
    if @recipe_type.save
      flash[:alert] = 'Tipo de receita cadastrada com sucesso'
      redirect_to new_recipe_type_path
    else
      flash.now[:alert] = 'Tipo de receita não cadastrada'
      render :new
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_params_id, only: %i[edit update show add_list published reviewed]
  before_action :set_recipe_types_and_cuisines, only: %i[edit update new create]
  before_action :authenticate_user!, only: %i[new create edit update list_pendind]
  before_action :authorized_admin, only: %i[list_pending published reviewed]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(set_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
    else
      flash.now[:alert] = 'Não foi possível salvar a receita'
      render :new
    end
  end

  def edit; end

  def update
    if @recipe.update(set_params)
      redirect_to @recipe
    else
      flash.now[:alert] = 'Não foi possível salvar a receita'
      render :edit
    end
  end

  def show
    if current_user
      @recipe_list = current_user.recipe_lists
    end
  end

  def search
    @recipe = Recipe.where('title LIKE ?', "%#{params[:name]}%")
  end

  def my_recipes
    @recipes = current_user.recipes
  end

  def add_list
    @recipe_list = RecipeList.find(params[:id])
    @recipe_list_item = RecipeListItem.new(recipe_id: @recipe.id,
                                            recipe_list_id: @recipe_list.id)
    if @recipe_list_item.save
      flash[:notice] = 'Receita adicionada com sucesso'
      redirect_to @recipe
    else
      flash[:alert] = 'Esta receita já esta incluida nesta lista'
      render :show
    end
  end

  def list_pending
    @recipes = Recipe.all
  end

  def published
    if @recipe.published!
      flash[:notice] = 'Receita publicada com sucesso'
      redirect_to :list_pending
    end
  end

  def reviewed
    if @recipe.reviewed!
      flash[:notice] = 'Receita rejeitada'
      redirect_to :list_pending
    end
  end

  private

  def authorized_admin
    return redirect_to root_path unless current_user.admin?
  end

  def set_params_id
    @recipe = Recipe.find(params[:id])
  end

  def set_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id, :difficulty,
                                    :cook_time, :ingredients, :cook_method, :user_id)
  end

  def set_recipe_types_and_cuisines
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Entrar', new_user_session_path %>
    <% end %>

    <%= form_tag search_path, method: 'get' do %>
      <%= label_tag :name, 'Buscar' %>
      <%= text_field_tag :name %>
      <%= submit_tag 'Buscar' %>
    <% end %>

    <%= alert %>
    <%= notice %>
    <%= yield %>
  </body>
</html>

app/views/recipe_lists/my_list.html.erb
<h3>Listas do usuário <%= current_user.email %></h3>

<% @recipe_lists.each do |recipe_list| %>
  <%= link_to recipe_list.name, recipe_list %>
  <% @recipe_list_items.each do |recipe_item| %>
    <%= recipe_item.recipe.title %>
  <% end %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/recipe_lists/new.html.erb
 <%= form_for @recipe_list do |f| %>
    <%= f.label :name, 'Nome da lista' %>
    <%= f.text_field :name %>
    <%= f.submit 'Criar lista' %>
  <% end %>

app/views/recipe_lists/show.html.erb
<h3>Lista de <%= @recipe_list.name %></h3>

app/views/recipe_types/_form.html.erb
<h1> Cadastrar Tipo de Receita </h1>

<%= form_for @recipe_type do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/recipe_types/new.html.erb
<%= render partial: 'form' %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>
  <%= f.label :recipe_type_id, 'Tipo da Receita' %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
  <%= f.label :cuisine_id, 'Cozinha' %>
  <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>
  <%= f.label :difficulty, 'Dificuldade' %>
  <%= f.text_field :difficulty %>
  <%= f.label :cook_time, 'Tempo de Preparo' %>
  <%= f.number_field :cook_time %>
  <%= f.label :ingredients, 'Ingredientes' %>
  <%= f.text_area :ingredients %>
  <%= f.label :cook_method, 'Como Preparar' %>
  <%= f.text_area :cook_method %>
  <%= f.submit 'Enviar' %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/recipes/edit.html.erb
<% if current_user && current_user.is_owner?(@recipe)%>
  <%= render partial: 'form' %>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>

app/views/recipes/index.html.erb
<h1>My CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>

<% if user_signed_in? %>
  <%= link_to 'Enviar uma receita', new_recipe_path %>
  <%= link_to 'Minhas receitas', my_recipes_path %>
  <%= link_to 'Criar lista de receitas', new_recipe_list_path %>
  <%= link_to 'Ver listas', my_list_path %>
  <% if current_user.admin? %>
    <%= link_to 'Receitas pendentes', list_pending_path %>
  <% end %>
<% end %>
<%= link_to 'Enviar tipo de receita', new_recipe_type_path %>

<% @recipes.each do |recipe| %>
  <% if recipe.published? %>
    <h1><%= link_to recipe.title, recipe %></h1>
    <ul>
      <li><%= recipe.recipe_type.name %></li>
      <li><%= recipe.cuisine.name %></li>
      <li><%= recipe.difficulty %></li>
      <li><%= recipe.cook_time_min %></li>
    </ul>
  <% end %>
<% end %>

app/views/recipes/list_pending.html.erb
<% @recipes.each do |recipe| %>
  <div id="recipe-<%= recipe.id %>">
    <h3><%= link_to recipe.title, recipe %></h3>
    <%= recipe.status %> <br>
    <%= link_to 'Published', published_recipe_path(recipe), method: :post %>
    <%= link_to 'Reviewed', reviewed_recipe_path(recipe), method: :post %>
  </div>
<% end %>

app/views/recipes/my_recipes.html.erb
<h1>Minhas receitas</h1>
<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time_min %></li>
  </ul>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/recipes/search.html.erb
<% if @recipe.any? %>
  <% @recipe.each do |recipe| %>
    <h3><%= link_to recipe.title, recipe %></h3>
    <ul>
      <li><%= recipe.recipe_type.name %></li>
      <li><%= recipe.cuisine.name %></li>
      <li><%= recipe.difficulty %></li>
      <li><%= recipe.cook_time_min %></li>
    </ul>
  <% end %>
<% else %>
    <h3> Receita não encontrada </h3>
<% end %>

app/views/recipes/show.html.erb
<h1> <%= @recipe.title %> </h1>
<h3> Detalhes </h3>
<p> <%= @recipe.recipe_type.name %> </p>
<p> <%= @recipe.cuisine.name %> </p>
<p> <%= @recipe.difficulty %> </p>
<p> <%= @recipe.cook_time_min %> </p>
<h3> Ingredientes </h3>
<p> <%= @recipe.ingredients %> </p>
<h3> Como Preparar </h3>
<p> <%= @recipe.cook_method %> </p>
<p> Receita enviada por <%= @recipe.user.email %> </p>

<% if user_signed_in? %>
  <%= form_tag add_list_recipe_path do %>
    <%= label_tag :name, 'Lista' %>
    <%= select_tag :name, options_from_collection_for_select(@recipe_list, :id, :name) %>
    <%= submit_tag 'Adicionar' %>
  <% end %>
  <% if (current_user && current_user.is_owner?(@recipe)) || current_user.admin? %>
    <%= link_to 'Editar', edit_recipe_path %>
  <% end %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/users/my_recipe_list.html.erb
<h3>Listas do usuário <%= current_user.email %></h3>

<% @recipe_lists.each do |recipe_list| %>
  <%= link_to recipe_list.name, recipe_list %>
<% end %>

<%= link_to 'Voltar', root_path %>